version: "3.8"
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/frontend/src
      - /frontend/node_modules
    stdin_open: true
    tty: true
    networks:
      - mern-ecommerce

networks:
  mern-ecommerce:
    driver: bridge
    external: false
    name: mern-ecommerce